[["C:/Users/erino/anaconda3/envs/mydev/Lib/site-packages/exceptiongroup/__init__.py",[false,[["__all__",true,13,null],["catch",true,2,["catch","C:/Users/erino/anaconda3/envs/mydev/Lib/site-packages/exceptiongroup/_catch.py",12]],["BaseExceptionGroup",true,2,["BaseExceptionGroup","C:/Users/erino/anaconda3/envs/mydev/Lib/site-packages/exceptiongroup/_exceptions.py",5]],["ExceptionGroup",true,2,["ExceptionGroup","C:/Users/erino/anaconda3/envs/mydev/Lib/site-packages/exceptiongroup/_exceptions.py",5]],["format_exception",true,2,["format_exception","C:/Users/erino/anaconda3/envs/mydev/Lib/site-packages/exceptiongroup/_formatting.py",12]],["format_exception_only",true,2,["format_exception_only","C:/Users/erino/anaconda3/envs/mydev/Lib/site-packages/exceptiongroup/_formatting.py",12]],["print_exc",true,2,["print_exc","C:/Users/erino/anaconda3/envs/mydev/Lib/site-packages/exceptiongroup/_formatting.py",12]],["print_exception",true,2,["print_exception","C:/Users/erino/anaconda3/envs/mydev/Lib/site-packages/exceptiongroup/_formatting.py",12]]]]]]